services:
  storybook:
    build: .
    ports:
      - "8080:80"
    develop:
      watch:
        - action: rebuild
          path: "."
          ignore:
            - .idea
            - .vscode
            - dist
            - node_modules
