services:
  dev:
    build:
      target: development
    volumes:
      - .:/app
    ports:
      - "6006:6006"
    command:
      - "/bin/bash"
      - "-c"
      - "npm install && npm run storybook"
