name: CI

on:
  push:
    branches:
      - main
      - renovate/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
      - name: Upload static files as artifact
        if: endsWith(github.ref, 'refs/heads/main')
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: storybook-static/
      - name: Upload library as artifact
        if: startsWith(github.ref, 'refs/tags/')
        id: library
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: dist/

  pages_deploy:
    if: endsWith(github.ref, 'refs/heads/main')
    needs: build
    name: 'GitHub Pages deployment'
    runs-on: ubuntu-24.04
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    name: 'Publish NPM package'
    runs-on: ubuntu-24.04
    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Download library as artifact
        uses: actions/download-artifact@v4
        with:
          name: library
          path: dist/
      - if: env.NPM_AUTH_TOKEN != ''
        name: Publish library
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
