name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
      - name: Upload static files as artifact
        if: endsWith(github.ref, 'refs/heads/main')
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/

  pages_deploy:
    if: endsWith(github.ref, 'refs/heads/main')
    needs: build
    name: 'GitHub Pages Deployment'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Download static files as artifact
        id: deployment
        uses: actions/deploy-pages@v4
