name: Linters

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  prettier:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Run prettier
        run: |
          npm install
          npx prettier --list-different src/

  eslint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Run eslint
        run: |
          npm install
          npx eslint .

  conventional_commits:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Run conventional commits
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          npm install
          echo "$TITLE" | npx commitlint
