name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    env:
      PAT_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - if: env.PAT_TOKEN != ''
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
